apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    app: user-service
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: microservices
data:
  SERVICE_NAME: "user-service"
  ENVIRONMENT: "base"
  PORT: "8081"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "users"
