apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: microservices
data:
  SERVICE_NAME: "frontend"
  ENVIRONMENT: "base"
  PORT: "80"
  API_GATEWAY_URL: "http://api-gateway:8080"
